export const ActionTypes = {

	SET_APP_MODE: 'SET_APP_MODE',
	SET_DIRECTORY_SEARCH_MODE: 'SET_DIRECTORY_SEARCH_MODE',
	SET_DIRECTORY_SEARCH_TEXT: 'SET_DIRECTORY_SEARCH_TEXT',
	SET_DIRECTORY_SEARCH_TAG: 'SET_DIRECTORY_SEARCH_TAG'
}

export function setAppMode(mode) {

	return { type: ActionTypes.SET_APP_MODE, mode }
} 

